datacommonsorg/mixer

- README.md
- go.sum
- store/arc.go
- util/util.go
Will use the same util function for the rest of the API methods wherever appropriate.
> Util function to read BT rows in batch and in parallel, and use that in GetPropertyValues/Labels.

- server/main.go
> Fix a bug for default GetPropertyValue limit.

- deployment/gke.sh
fix comment out code in gke.sh
> fix comment out code in gke.sh

- deployment/README.md
- deployment/gke.sh
- deployment/prod_bq_dataset.txt
- deployment/staging_bq_dataset.txt
Add bq_dataset.txt for both staging and prod. 
Udpate gke.sh to take in bq_dataset from the test file. 
Udpate README
> make bq_dataset configurable through bq_dataset.txt

- golden_response/staging/property-labels-states.json
Expected changes caused by:
https://github.com/datacommonsorg/mixer/pull/220
> [golden response] Add new expected labels at the state level

- golden_response/prod/property-labels-states.json
> [golden response] Add new expected labels at the state level for prod

- e2etest/get_property_values_test.go
- golden_response/staging/get_property_values/limit.json
- server/property_value.go
- server/property_value_test.go
The limit function was missed during the last big refactor. Now we have tests...
> Fix GetPropertyValue limit bug

- cloud_automation/airflow/dag.py
- cloud_automation/airflow/variables.json
Creates airflow workflow which does the following:
1) trigger dataflow job in the other PR.
2) Write success/failure status to GCS.
@pradh : Can you help review this.
> Create airflow workflow.

- golden_response/prod/get_property_values/contained_in_place.json
- golden_response/prod/get_property_values/name.json
- golden_response/prod/get_triples/place.json
- golden_response/prod/query/name.json
> Copy over golden files to prod for 2020_08_06_01_02_58

- e2etest/get_stat_ranking_test.go
- e2etest/setup.go
- golden_response/staging/get_stat_ranking/california.json
- golden_response/staging/get_stat_ranking/country.json
- proto/mixer.proto
- server/model.go
- server/places.go
Added a new endpoint to simplify the arguments and make it less error prone
> Add new protobuf based endpoint for stat var rankings

- e2etest/get_stat_ranking_test.go
- golden_response/staging/get_stat_ranking/california.json
- golden_response/staging/get_stat_ranking/country.json
- golden_response/staging/get_stat_ranking/crime_percapita.json
- proto/mixer.proto
- server/places.go
Also changes it to a get request.
Apologies for the formatting changes in mixer.proto -- mostly fixing indents, whitespace, and long lines. I enabled format on save in my editor, and figure this is good cleanup. Let me know if you'd rather I revert it.
The changes in the golden files are also mostly whitespace, except for the new file.
> Add per-capita option to GetLocationRanking

- e2etest/get_landing_page_data_test.go
- golden_response/staging/get_landing_page_data/city.json
- server/landing_page.go
- Also filter out nearby place with population < 10000
- Also remove zipcode from parent places
> Fetch stat var data that are missing from landing page cache

- golden_response/staging/get_landing_page_data/city.json
- golden_response/staging/get_landing_page_data/country.json
- golden_response/staging/get_landing_page_data/county.json
- server/landing_page.go
- server/model.go
Response to comment on https://github.com/datacommonsorg/website/pull/494
> Add chosen child type to landing page data response

- e2etest/get_stat_ranking_test.go
- golden_response/staging/get_stat_ranking/crime_percapita.json
previously did not pass on per capita arg.
> Fix golden response for stat ranking

- cloudbuild.binarydatapush.yaml
- cloudbuild.datapush.yaml
- cloudbuild.test.yaml
- golden_response/staging/statvar_ranking/missing_Earth_country_rankings.json
- golden_response/staging/statvar_ranking/missing_USA_city_rankings.json
- golden_response/staging/statvar_ranking/missing_USA_county_rankings.json
- golden_response/staging/statvar_ranking/missing_USA_state_rankings.json
- main.go
- prepare-proto.sh
- server/landing_page.go
- server/memcache.go
- server/server.go
Still seeing mixer OOM after https://github.com/datacommonsorg/mixer/pull/352. Try explicit gc here.
Some background read: https://stackoverflow.com/questions/37382600/cannot-free-memory-once-occupied-by-bytes-buffer/37383604#37383604
> Try to force garbage collection of unused branch cache memory

- main.go
This is to enable prod to gcp access.
> Use ALTS server credential

- golden_response/prod/get_stats/census_pep.json
- golden_response/prod/get_stats/median_age.json
Will merge after pushing to prod
> Updating prod goldens from 2020_11_12_01_01_15 release

- proto/mixer.proto
> Make /place/stat-vars POST endpoints

- proto/mixer.proto
- server/places.go
- server/places_test.go
Add GetPlaceStatVarsUnion API at "/place/stat-vars/union"
> Add GetPlaceStatVarsUnion API

- server/stat.go
- server/stats.go
This is a pure function move without any change.
Later on will make stat.go as stat_util.go and stats.go will only contains API  level function impl.
> Move GetStat() function from stat.go to stats.goto prepare more refactor

- proto/mixer.proto
- server/populations.go
- server/populations_test.go
- server/triple.go
This is never used; We will have a server level flag to enable branch cache.
> Remove per-request branch cache option

- deployment/minikube/README.md
- deployment/minikube/generate_yaml.sh
- deployment/template/mixer.yaml.tmpl
- main.go
One it's ready, we just need to set this to "false" to the mixer deployment code in cloud source repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/402)
> Add a boolean flag to enable branch cache

- internal/server/place_stat_vars.go
- internal/server/places.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/404)
> Separate place stat vars related APIs in a separate file

- cmd/main.go
- deploy/base/deployment.yaml
- deploy/base/namespace.yaml
- deploy/overlays/dev/patch_deployment.yaml
- deploy/overlays/dev/patch_esp.yaml
- deploy/storage/kustomization.yaml
- docs/developer_guide.md
- skaffold.yaml
- disable branch cache as the readiness probe will fail on Minikube (not sure why)
- make log working
- various fix for branch cache reload
> Improve Skaffold local dev process

- test/integration/golden_response/prod/get_stats/median_age.json
> Update prod golden data

- cmd/main.go
- internal/server/bigtable.go
- internal/server/property_label.go
- internal/server/server_test.go
- test/integration/bq_only_test.go
- test/integration/setup.go
This is to allow mixer to only connect to BigQuery and run Sparql without setting up BigTable.
> Add a flag so mixer can run in BigQuery only mode

- build/ci/cloudbuild.goldendiff.yaml
- script/golden_diff_notify.sh
- tools/send_diff_email/main.go
- tools/send_email/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/451)
> Send notification email on golden data diff from a new base Bigtable

- internal/server/populations.go
- internal/server/populations_test.go
Most places have covid data and requires merge of base and branch cache. Current impl do the unzip-unmarshal sequential and leads to very long process time
> Parallel process popobs base and branch cache

- test/integration/golden_response/staging/statvar_ranking/missing_USA_city_rankings.json
- test/integration/golden_response/staging/statvar_ranking/missing_USA_county_rankings.json
- test/integration/golden_response/staging/statvar_ranking/missing_USA_state_rankings.json
We may want to move this test to website repo? @beets
> Fix ranking test from chart config change

- build/ci/cloudbuild.goldendiff.yaml
This group allow external sender to post.
> Change golden diff notification recipient to datacommons-alerts@

- test/integration/curry_test.go
- test/integration/golden_response/staging/curry/mw.json
- test/integration/golden_response/staging/curry/ur.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/471)
> Guard curry data update

- cmd/main.go
- deploy/base/deployment.yaml
- deploy/overlays/autopush/kustomization.yaml
- deploy/overlays/custom/kustomization.yaml
- deploy/overlays/dev/kustomization.yaml
- deploy/overlays/encode/kustomization.yaml
- deploy/overlays/encode/patch_bigquery.yaml
- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/staging/kustomization.yaml
- deploy/overlays/statvar/kustomization.yaml
- deploy/storage-statvar/kustomization.yaml
- deploy/storage-statvar/store.project
- deploy/storage/kustomization.yaml
- deploy/storage/store.project
- docs/developer_guide.md
- internal/server/server.go
- internal/server/stat_series.go
- scripts/deploy_gke.sh
- test/integration/setup.go
This is to prepare for the stat var obs migration
> Add a mixer flag for store project and simplify other flags

- build/ci/cloudbuild.goldendiff.yaml
- scripts/golden_diff_notify.sh
- test/integration/get_stat_all_test.go
- test/integration/get_stat_collection_test.go
- test/integration/get_stat_series_test.go
- test/integration/get_stat_set_series_test.go
- test/integration/get_stat_set_test.go
- test/integration/get_stats_test.go
There are two issues:
* The base cache version in SVOBS mode should be updated
* when generate_golden is True, should only update golden files but not run tests
> Fix bugs of golden diff notification

- docs/developer_guide.md
Added "Generate Go proto files" section, so release guide can refer it
> Update mixer developer guide

- scripts/golden_diff_notify.sh
Instead of golden data diff, sometimes there are test failure from data change. Adding this to catch that
> Send notifiy email if there is test failure

- build/ci/cloudbuild.push.yaml
- build/push_go_protoc_image.sh
- deploy/push_deploy_tool_image.sh
- scripts/push_binary.sh
- Move docker build script to reside in the same folder as Dockerfile.
- Make a new script to build and push binaries from local code
> Update mixer deploy scripts

- deploy/overlays/autopush/kustomization.yaml
- deploy/overlays/dev/kustomization.yaml
- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/staging/kustomization.yaml
Autopush should be updated after this PR is submitted.
For next week's release, we don't need other code change, can just verify this in staging and then deploy to prod.
> Use svobs mode for mixer deployment

- cmd/main.go
- internal/server/server.go
- internal/server/statvar_hierarchy_util_test.go
Tested locally, will verify after pushing to autopush
> Delete branch cache subscriber on mixer server shutdown

- internal/proto/mixer.pb.go
- internal/proto/mixer_grpc.pb.go
- internal/server/place_stat_vars.go
- proto/mixer.proto
- test/integration/get_place_statvars_union_test.go
The current response has an unnecessary nested layer, flatten it and created a new endpoints with prefix /v1.
> Flatten the response for /place/stat-vars/union

- test/integration/golden_response/get_statvar_group_node/citizenship.json
- test/integration/golden_response/get_statvar_group_node/demographics.json
- test/integration/golden_response/get_statvar_group_node/demographics_gbr.json
- test/integration/golden_response/get_statvar_group_node/root.json
- test/integration/golden_response/get_statvar_group_node/root_mtv.json
- test/integration/golden_response/get_statvar_group_node/root_mtv_jpn.json
- test/integration/golden_response/get_statvar_group_node/school.json
- test/integration/golden_response/get_statvar_summary/females.json
- test/integration/golden_response/get_statvar_summary/total_crimes.json
- test/integration/golden_response/search_statvar/asian_age.json
- test/integration/golden_response/search_statvar/female.json
> Update Golden Files

- cmd/main.go
- docs/developer_guide.md
- internal/store/memdb.go
- Now have a flag for each storage: bigquery, base bigtable, branch bigtable and gcs.
- Read tmcf and csv from GCS, parse tmcf into table schema and read in csv rows.
- Next step is to construct time series from each csv row based on table schema.
> [tmcf + csv] Load tmcf and csv from GCS; Update server flags

- internal/server/place_stat_vars.go
- internal/server/statvar_group.go
- internal/store/memdb.go
- test/integration/get_place_statvars_test.go
- test/integration/get_place_statvars_union_test.go
- test/integration/golden_response/get_statvar_group_node/root.json
- test/integration/golden_response/get_statvar_group_node/root_mtv.json
- test/integration/golden_response/get_statvar_group_node/root_mtv_jpn.json
- test/integration/golden_response/get_statvar_path/memdb.json
This is used by scatter tool.
Also fixed stat var path bug for private stat vars
> [Private DC] Support API for /place/stat-vars, /v1/place/stat-vars/union

- test/integration/place_statvar_ranking_test.go
This is to make the test passing after website change: https://github.com/datacommonsorg/website/pull/1141
> Update place stat var ranking test

- internal/server/place_page.go
This is causing mixer crash and server restart in production: https://pantheon.corp.google.com/errors;service=gke_instances;time=P1D?project=datcom-website-prod
We should deploy this fix to prod ASAP
> Fix a nil pointer deref in mixer

- internal/server/place/place_stat_date.go
- internal/server/stat/stat_point.go
- internal/server/stat/stat_series.go
- internal/store/bigtable/key.go
This address the issue: https://github.com/datacommonsorg/mixer/issues/683
> Split d/f/ cache type to three difference cache types.

- cmd/main.go
- deploy/overlays/dev/kustomization.yaml
- deploy/overlays/dev/patch_args.yaml
Also use import group for dev deployment
> Import group branch cache subscriber update

- internal/server/biopage/bio_page.go
- internal/server/node/triple.go
- internal/server/placein/placein.go
- internal/server/placepage/place_page.go
- internal/server/recon/id.go
- internal/server/stat/stat_reader.go
- internal/server/statvar/place_stat_vars.go
Fix BaseData naming, which is a pre import group concept.
> Fix inconsistent naming

- internal/proto/stat_var.pb.go
- internal/server/statvar/count.go
- proto/stat_var.proto
this message will be shared with Source/Dataset existence
the structure of the message has not changed, only the name
> update PlaceStatVarExistence to EntityStatVarExistence

- internal/server/recon/resolve.go
Fix related to issue: https://github.com/datacommonsorg/import/issues/181
> Add support for countryAlpha3Code and countryNumericCode in resolve.go

- esp/endpoints.yaml.tmpl
- scripts/deploy_gke.sh
The selector needs to use the "apis.name" not "endpoints.name" field
> Fix misconfiged API endpoints selector

- deploy/helm_charts/envs/mixer_autopush.yaml
Main change: default (non-svg) service: 2 x 2G memory -> 15 x 3G memory
> Scale up mixer autopush

- .gitignore
- deploy/helm_charts/envs/mixer_dev.yaml
- deploy/helm_charts/envs/mixer_encode.yaml
- deploy/helm_charts/envs/mixer_private.yaml
- scripts/deploy_gke.sh
With this, I have redeployed mixer_private
> Fix a few release config issue

- deploy/helm_charts/mixer/templates/config_maps.yaml
Reverts datacommonsorg/mixer#943
Reverting to see if this fixes the timeout
> Revert "Add quote to some helm templated values"

- deploy/helm_charts/mixer/templates/config_maps.yaml
This is currently causing autopush to fail to be deployed in GCP.
> Unquote schema mapping

- internal/server/place/places.go
Temporary fix to get most complete ranking for Count_Person across mulitple import groups
> temporary ranking fix

- internal/server/v1/info/golden/bulk_variable_group_info/economy.json
- internal/server/v1/info/variable_group.go
Calls the simple version of the API VariableGroupInfo() concurrently to get the bulk response.
> Update /v1/bulk/info/variable-group with richer response data

- internal/server/ranking/ranking.go
Move comments above each block to make it more readable
> Add ranking for import NASA_NEXGDDP_CMIP6_Subnational_AggrDiffStats_LongRangeProjections

- cmd/main.go
- test/setup.go
> Use datcom-store as bigquery billing account for testing

- internal/proto/stat.pb.go
- proto/stat.proto
adding to SourceSeries and StatMetadata
> add is_dc_aggregate/is_dc_imputed

- docs/developer_guide.md
- esp/envoy-config.yaml
Submitted #1040 too early, this is the actual update for the docs. Sorry about this @shifucun
> Update missing docs for envoy

- deploy/mapping/kustomization.yaml
- deploy/storage/kustomization.yaml
Reverts datacommonsorg/mixer#1044
Please see https://github.com/datacommonsorg/website/pull/2347 for context.
> Revert "Remove configmap suffix for kustomize files referenced by website kustomize files."

- internal/proto/mixer.pb.go
- internal/proto/mixer_grpc.pb.go
- internal/proto/recon.pb.go
- internal/server/handler.go
- internal/server/handler_v1.go
- internal/server/recon/recognize_places.go
- proto/mixer.proto
- proto/recon.proto
This is trying to migrate https://github.com/datacommonsorg/website/pull/2417/files# to Mixer.
> Add endpoint for RecognizePlaces.

- README.md
Add doc on how to do 'g4 sync'.
> Add doc on how to do 'g4 sync'.

- deploy/helm_charts/mixer/templates/deployment.yaml
- deploy/helm_charts/mixer/values.yaml
As discussed offline, disabled it for custom instances. The values will be set in the website repo.
> [Custom DC] disable branch cache for custom instances

- deploy/helm_charts/envs/mixer_private.yaml
- deploy/helm_charts/envs/mixer_prod.yaml
- deploy/helm_charts/envs/mixer_staging.yaml
- deploy/helm_charts/envs/mixer_stanford.yaml
- deploy/helm_charts/mixer/templates/config_maps.yaml
- deploy/helm_charts/mixer/templates/deployment.yaml
- deploy/helm_charts/mixer/values.yaml
- internal/server/server.go
- internal/server/statvar/statvar_hierarchy_util.go
- internal/server/statvar/statvar_hierarchy_util_test.go
- Get blocklisted svgs from environment file
- set blocklisted svgs file in each helm chart
works together with https://github.com/datacommonsorg/website/pull/2627
> [stat var hierarchy] separate blocklist svgs for each environment

- internal/server/v2/propertyvalues/api.go
- internal/server/v2/propertyvalues/golden/containedin/CA_county.json
- internal/server/v2/propertyvalues/golden/containedin/USA_county.json
This is to match the general property values response (also matching V1)
> Return name for containedInPlace+ node API

- internal/server/stat/stat_reader.go
- internal/store/bigtable/group.go
This way, dcbranch could be used to block/override bad data.
> Always prefer dcbranch over other import groups

- cmd/main.go
- docs/developer_guide.md
- examples/sqlite/main.go
- internal/server/data/import.go
- internal/server/resource/resource.go
- internal/server/server.go
- internal/server/statvar/count.go
- internal/server/v1/propertyvalues/core.go
- internal/server/v2/propertyvalues/golden/triple_in/result1.json
- internal/server/v2/propertyvalues/golden/triple_out/result.json
- internal/sqldb/sqlite/sqlite.go
- internal/sqldb/util.go
- internal/sqldb/writer.go
- internal/util/util.go
* CreateTable() func to create tables as a one time setup
* Branch some SQL syntax that are not compatible between sqlite and mysql
* Use sqlDataPath to represent raw csv data path. TODO: make this working for GCS path.
> Consolidate logic between sqlite and mysql

- internal/merger/merger.go
- internal/merger/merger_test.go
Added tests for empty local mixer response.
> Fix a mixer merger bug when local mixer returns empty observation response

- .gitignore
- internal/sqldb/writer.go
The raw csvs are processed via import tool, so no need to resolve in mixer again.
> SQL database input csv files should be have been resolved

- .gitignore
- internal/sqldb/csv.go
- internal/sqldb/gcs.go
- internal/sqldb/writer.go
Also did some minor refactor to clean up the structure.
> [RSI] Read triples csv (from RSI script) instead of generating them

- internal/server/statvar/count.go
- internal/sqldb/query/check_sv.go
- internal/sqldb/query/check_svg.go
- internal/sqldb/query/count_observation.go
Created a few existence related query functions and use them in the existence check API
> Create a package to hold SQL query functions

- .gitignore
- cmd/main.go
- docs/developer_guide.md
- internal/server/cache/cache.go
- internal/server/count/count.go
- internal/server/handler_core.go
- internal/server/v2/observation/contained_in.go
- internal/server/v2/observation/direct.go
- internal/server/v2/observation/helper.go
- internal/sqldb/sqlquery/check_sv.go
- internal/sqldb/sqlquery/count_observation.go
- internal/sqldb/sqlquery/entity_variable.go
- internal/sqldb/sqlquery/entity_variable_existence.go
- internal/sqldb/sqlquery/get_provenance.go
- internal/util/util.go
- internal/util/util_test.go
- test/setup.go
* Query all <entity, variable> pair from custom DC SQL database and cache them in-memory
* Improve the count function by using this cache information.
> Cache entity variable existence from SQL database

- deploy/helm_charts/mixer/templates/deployment.yaml
update deployment config to be used with: https://github.com/datacommonsorg/website/pull/3978
> update deployment yaml

- internal/server/v1/observations/calculator.go
- internal/server/v1/propertyvalues/core.go
- internal/server/v2/observation/contained_in.go
- internal/sqldb/sqlquery/entity_variable_existence.go
Remove unused variables and mis-ref variables.
> Fix some small no-op issues in mixer

- internal/store/files/WorldGeosForPlaceRecognitionAlternateNames.csv
- internal/store/files/recog_place_store_test.go
> Add `us` to USA

- internal/server/v2/observation/calculation_util.go
- internal/server/v2/observation/calculation_util_test.go
Step 1 of computing calculations: This just finds the holes from the base response which will be candidates for calculation
> [calculations] Add findObservationResponseHoles

- internal/server/v2/observation/calculation_util.go
- internal/server/v2/observation/calculation_util_test.go
> Add functions for computing candidate series and calculating one step of formula

- build/ci/cloudbuild.push.yaml
Also make build step order explicit.
> Add repo version bump to push trigger config

- internal/store/files/BogusPlaceNames.csv
For queries like: https://datacommons.org/explore/#q=annual+growth+rate+of+real+gdp+per+employed+person+in+the+world&client=ui_query
> Added "real" to bogus place names

- deploy/helm_charts/envs/mixer_autopush.yaml
- deploy/helm_charts/envs/mixer_prod.yaml
- deploy/helm_charts/envs/mixer_staging.yaml
Re-issued the cert to include additional SANs. See https://docs.google.com/document/d/1i-TJNxjpAobi6fos-ZJYIV94eM6d2v2v-lbo4lu0MxQ/r/0-cR8M_V0NdxfG91Asz3TUzw/edit?tab=t.0#bookmark=id.odmz7xpexgip
> Update references to multi-domain cert

- deploy/apigee/README.md
- deploy/apigee/deploy_apigee.sh
- deploy/apigee/envs/nonprod.yaml
- deploy/apigee/envs/prod.yaml
- deploy/apigee/policies/enforce-quota-limit.template.xml
- deploy/apigee/policies/rewrite-quota-exceeded-message.template.xml
- deploy/apigee/proxies/api.xml
- deploy/apigee/sample.env
- deploy/apigee/sync_env.sh
- deploy/apigee/target_endpoints/api.template.xml
- deploy/apigee/terraform/prod/main.tf
- Use Secrets Manager for *.env files
- Add quota limit for trial API key
- Upgrade environment type to handle more QPS
> Improve Apigee deployment

- internal/server/search/search.go
* Unfortunately there are no golden tests for this (likely because it's BQ, hence expensive?) so tested them manually by starting a local server:
> Parameterize BQ query for search endpoint.

- internal/sqldb/sqlquery/observation.go
* Tested via successful run of https://github.com/datacommonsorg/mixer/blob/860e4da8e48f7ad56f059df15fc256280eaad50b/internal/server/v2/observation/golden/direct_test.go#L4
> Parameterize sql query for observations.

- gke/setup_robot_account.sh
Reduced from roles/bigquery.admin to roles/bigquery.dataViewer
> Updated mixer service account bigquery permissions

- internal/translator/translate.go
Adds a length check to not try to strip quotes when the string is just a "
> Fix the posisble index out of bounds error on stripping quotes.

- internal/server/spanner/golden/query/search_nodes_with_type.json
- internal/server/spanner/golden/query/search_nodes_without_type.json
- internal/server/spanner/golden/query_test.go
- internal/server/spanner/model.go
- internal/server/spanner/query.go
* This PR adds support in the db layer.
* API support will be added in follow-up PRs.
* Decided to always limit it to max 100 results. Can add support for user specified limit later if needed.
> Add support for node search.

- deploy/README.md
- deploy/helm_charts/envs/mixer_autopush.yaml
- deploy/helm_charts/mixer/templates/config_maps.yaml
- deploy/helm_charts/mixer/templates/deployment.yaml
- deploy/helm_charts/mixer/values.yaml
- docs/remote_mixer.md
- internal/server/spanner/golden/query/get_node_props_by_object_id.json
- internal/server/spanner/query.go
- internal/server/v3/observation/golden/observation_test.go
- scripts/deploy_gke.sh
I can try deploying autopush once submitted
This doesn't yet remove EnableSpannerGraph since some of the tests seem flaky (I can look into this separately)
> Enable spanner graph on mixer autopush

- cmd/main.go
- go.mod
- go.sum
- internal/server/v2/observation/contained_in.go
- internal/server/v2/observation/direct.go
- internal/sqldb/client.go
- internal/sqldb/model.go
- internal/sqldb/query.go
- internal/sqldb/sqlquery/observation.go
- internal/sqldb/statements.go
- test/setup.go
* Encapsulates the observations query in sql client.
* It also brings in the sqlx library that allows us to do parameterized named queries and model the sql client in line with the spanner client.
> Encapsulate observations query in sql client.

- internal/server/redis/client.go
- internal/server/redis/client_test.go
- internal/server/redis/processor.go
- internal/server/redis/processor_test.go
* Next: redis configuration, wire the processor.
> Create redis cache processor.

- internal/server/datasource/datasource.go
- internal/server/remote/client.go
- internal/server/remote/datasource.go
- internal/server/spanner/client.go
- internal/server/spanner/datasource.go
This will be used to identify between multiple datasources of the same type (particularly for pagination)
> Add Id() to datasource

- internal/server/spanner/golden/query/get_node_edges_by_subject_id.json
- internal/server/spanner/golden/query/get_node_edges_out_bracket_props.json
- internal/server/spanner/statements.go
Fixes the sorting one of the spanner queries to be more stable
> Fix sorting order

- internal/server/pagination/pagination.go
- internal/server/pagination/pagination_test.go
- internal/server/spanner/dsutil.go
- internal/server/v3/node/golden/node_test.go
- internal/server/v3/node/golden/pagination_first_page.json
- internal/server/v3/node/golden/pagination_second_page.json
Will follow up with updated merging in https://github.com/datacommonsorg/mixer/pull/1552/files
> Update spanner pagination to use v2.Pagination

- cmd/main.go
- internal/metrics/metrics.go
- internal/server/handler_v2.go
- internal/server/mirror.go
- internal/server/mirror_test.go
- internal/server/server.go
For performance and accuracy comparisons
> Package to mirror requests to new V3 APIs
