datacommonsorg/mixer

deployment/template_deployment.yaml
dc4 was generated today based on yesterday's snapshot of ingested data.
=> Update cache version used by the mixer to dc4

deployment/docker_image.txt
This includes the branch cache for GetPropertyValue and new api /bulk/stats
=> Bump mixer version to 0.3.5

deployment/prod_bq_dataset.txt
Found by error "Project name needs to be separated by dot from dataset name, not by colon in table name"
=> Fix bug in BQ table path starting from PR 169

examples/check_bt.sh
The measurement method is moved out of the prefix.
=> Update bigtable prefix in check_bt tool

golden_response/staging/get_landing_page_data/city.json, golden_response/staging/get_landing_page_data/county.json, server/landing_page.go, server/model.go
The client needs to get display name like "San Jose, CA" from separate API call, so the name returned here is redundant. 
Remove to make it easier to use in client side.
=> Only return place dcids in landing page data

proto/mixer.proto, server/model.go, server/places.go, util/util.go
This API is never really used by any client, removing to save space and time for cache generation. For further usage, there is a ranking api that gets all the places ranking for a particular stat var
=> Remove interesting place API

deployment/minikube/README.md, e2etest/get_place_statsvar_test.go, e2etest/get_place_statvars_test.go, proto/mixer.proto, server/places.go
Once all clients are migrated over, can remove "/place/stats-var".
Tested in Minikube and looking fine
=> Add /place/stat-vars API (replacement for /place/stats-var)

Dockerfile, cloudbuild.binarydatapush.yaml, deployment/template/mixer.yaml.tmpl, healthcheck/healthchecker.go, main.go
- Mixer is  unavailable during rolling out due to the lack of health check, branch cache loading taking minutes and need to use startup probe to guard it.
- I suspect some of of the long latency we have seen is due to the lack of liveness check, adding liveness check to overcome that.
=> Add health check for mixer container

cloudbuild.binarydatapush.yaml, deployment/template/mixer.yaml.tmpl
See discussion: https://stackoverflow.com/a/61936155.
Basically without startupProbe, the liveness probe can timeout if server starts slow and restart it, making it an infinite loop.
=> Only use readiness probe since GKE does not support it until k8s 1.20 (currently stable version is 1.17)

go.mod, go.sum, script/update-golden-staging.sh, test/integration/get_landing_page_data_test.go, test/integration/get_observations_test.go, test/integration/get_place_statsvar_test.go, test/integration/get_place_statvars_test.go, test/integration/get_places_in_test.go, test/integration/get_pop_obs_test.go, test/integration/get_populations_test.go, test/integration/get_property_labels_test.go, test/integration/get_property_values_test.go, test/integration/get_related_locations_test.go, test/integration/get_stat_all_test.go, test/integration/get_stat_collection_test.go, test/integration/get_stat_ranking_test.go, test/integration/get_stat_series_test.go, test/integration/get_stat_set_test.go, test/integration/get_stat_test.go, test/integration/get_stat_value_test.go, test/integration/get_stats_test.go, test/integration/get_triples_test.go, test/integration/golden_response/staging/statvar_ranking/missing_Earth_country_rankings.json, test/integration/golden_response/staging/statvar_ranking/missing_USA_city_rankings.json, test/integration/golden_response/staging/statvar_ranking/missing_USA_county_rankings.json, test/integration/golden_response/staging/statvar_ranking/missing_USA_state_rankings.json, test/integration/place_statvar_ranking_test.go, test/integration/query_test.go
- Add t.Parallel() to all the integration tests.
- The TestChartConfigRankings ranking test have two for loops over place type (4) and chart config (>100) which takes about 60 seconds to run. Use goroutine to parallel at config level so the O(100) request can emit concurrently. Hence needs to sort the final result by chart title and updating the golden response.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/421)
=> Parallel integration tests to speed up from ~2min to 10s

cmd/main.go, internal/server/bigtable.go, internal/server/bigtable_test.go, internal/server/landing_page.go, internal/server/memcache.go, internal/server/model.go, internal/server/place_stat_date.go, internal/server/place_stat_vars.go, internal/server/places.go, internal/server/populations.go, internal/server/property_label.go, internal/server/property_label_test.go, internal/server/property_value.go, internal/server/server.go, internal/server/server_test.go, internal/server/stat_bt_reader.go, internal/server/stat_point.go, internal/server/stat_series.go, internal/server/testing.go, internal/server/triple.go, internal/server/triple_test.go, test/integration/setup.go
This is to prepare for reading from both base and branch BigTables.
bigTableReadRowsParallel now takes multiple tables. The first one should be the branch BT and second one the base BT. The result will rank the result by the table order and pick the data by that order when exists in both tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/441)
=> Support concurrent read of multiple BigTables

build/ci/cloudbuild.push.yaml
Turn off bucket level public access and only give individual object public access (b/174779035)
=> Make grpc descriptor public accessible

build/ci/cloudbuild.push.yaml, gke/setup_esp.sh, script/deploy_gke.sh
artifacts.datcom-ci.appspot.com holds the docker images. Separate out these files to make it safer to manage.
=> Use a new bucket to hold mixer grpc descriptor files

build/ci/cloudbuild.push.yaml, deploy/Dockerfile, deploy/README.md, deploy/base/deployment.yaml, deploy/gke/autopush.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/staging/kustomization.yaml, gke/config.yaml, scripts/deploy_gke.sh, scripts/update_autopush_version.sh, test/load_testing/locust-master-controller.yaml, test/load_testing/locust-worker-controller.yaml
autopush instance will be auto-deployed after each PR commit.
staging instance can only be manually deployed on demand.
also updated autopush/staging domain
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datacommonsorg/mixer/456)
=> Add config for mixer autopush deployment

internal/server/triple.go, test/integration/get_triples_test.go, test/integration/golden_response/staging/get_triples/observation_svobs.json, test/integration/golden_response/staging/get_triples/stat_var_svobs.json
We don't have materialized triples data in Cloud Bigtable for Observation, as it blows up the storage and it's only accessed for debugging.
This PR adds support to read triples for StatVarObservation through Sparql. It's reasonable fast.
=> GetTriples support for StatVar Observation node

deploy/base/ingress.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/prod/kustomization.yaml, deploy/overlays/staging/kustomization.yaml
For prod, staging and autopush deployment, self managed ssl certificate "multi-domain" is created in the load balancer.
This PR adds this certificate to the Ingress yaml file, so the managed and self created SSL would attach to the Ingress each time it is deployed.
=> Add self managed ssl certificate to applicable mixer deployment

internal/server/property_value.go
Currently readPropertyValues() function only uses the base cache [1], so it's unnecessary to perform cache merging. This currently incurs 2 Bigtable read, hence a much longer time for request that performs O(10K) row read.
[1] https://github.com/datacommonsorg/mixer/blob/542c6aebb26958a831019989a817560f67d48d8e/internal/server/property_value.go
=> Remove redundent cache merge in GetPropertyValue API

deploy/base/deployment.yaml, deploy/overlays/dev/patch_deployment.yaml
When debugging the mixer 5xx errors for long processing API with large amount data (stats of cities in US), I found it's due to the cpu and memory limit. When looking at the GKE monitoring, the peak cpu and memory are within the limit, however the behavior is not predictable. Client can get various 5xx errors, which may depending how the socket is terminated (mixer processing termination, restart or esp restart, etc.).
Turning off the limit has the following effect based on the [doc1](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/), [doc2](https://kubernetes.io/docs/concepts/policy/limit-range/) : Each Pod/Container can use the cpu/memory up to that of the cluster node, and when exceed, will result in OOM of the node, hence impacting other Pod.
Considering …
=> Do not set GKE pod cpu and memory limit

deploy/base/deployment.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/prod/kustomization.yaml, docs/developer_guide.md, internal/server/stat_point.go
Seeing pods getting evicted in autopush mixer due to memory issue. I saw several large peaks of requests to the auotpush mixer in the past days, which is a bit mysterious, as it should only take the web-driver tests. 
I investigated the cpu and memory usage a little more with logging locally. With resources limit set, mixer actually was able to complete a large request under 15s, but ESP does not return the response back. 
Check in logging here and deploy to GKE under real load for more investigation.
Compare with past version, also added "requests" field to ensure the cpu and mem allocation.
=> Add back GKE resource limit to future investigate ESP issue

internal/server/statvar_group.go, test/integration/get_statvar_path_test.go
This is a dummy node for linking the top level stat var groups, but not used by client.
=> Do not return stat var group (dc/g/Root) root when get path

internal/server/bigtable.go, internal/server/bigtable_test.go, internal/server/landing_page.go, internal/server/place_stat_vars.go, internal/server/places.go, internal/server/property_label.go, internal/server/property_value.go, internal/server/stat_bt_reader.go, internal/server/stat_point.go, internal/server/statvar_group.go, internal/server/statvar_search.go, internal/server/triple.go, test/integration/golden_response/search_statvar/female.json, test/integration/search_statvar_test.go
In case where there are O(10k) stat var dcids, it takes seconds to read the existence cache. Since we do filter at the end anyway, perform a pre-filter before lookup existence cache.
Also improves readability for functions with long list of arguments.
=> Speed up stat var search and improve bigtable read latency

deploy/base/deployment.yaml
To accommodate for the increased time to build stat var group and search index
=> Relax liveness/readiness prober time

internal/translator/translate.go, internal/translator/translate_test.go
This is responsible for the timeout of the following command:
`curl --request POST --url https://api.datacommons.org/query  --header 'content-type: application/json' --data '{ "sparql": "SELECT distinct ?d  WHERE { ?ccdt typeOf ChemicalCompoundDiseaseTreatment . ?ccdt compoundID ?c . ?c drugName Prednisone . ?ccdt diseaseID ?dis . ?dis commonName ?d }  LIMIT 10"}'`
and likely the cause for some of the previous bio queries where long Triples tables join are performed
=> Fix a translator bug that leads to infinite loop

internal/translator/translate.go, test/integration/golden_response/statvar_ranking/missing_Earth_country_rankings.json, test/integration/golden_response/statvar_ranking/missing_USA_city_rankings.json, test/integration/golden_response/statvar_ranking/missing_USA_county_rankings.json, test/integration/golden_response/statvar_ranking/missing_USA_state_rankings.json
This was introduced in https://github.com/datacommonsorg/mixer/pull/578. Both PRs try to solve the issues when current table has all been used in JOIN conditions, then need to pick a table to extend the join graph.
Also:
* Add some more comments
* Remove a over-done type alias
Need to update the landing page config tests here as well
=> Fix a bug when building SQL JOIN conditions

deploy/overlays/local/patch_deployment.yaml, docs/developer_guide.md, skaffold.yaml
- Reduce resources so minikube can restart a new deployment without first deleting current deployment. Note minikube should have > 2x memory of one deployment to make this work
- Change local deployment port to 8081, which matches the GKE port.
=> Update mixer local development config

internal/server/statvar_group.go, internal/store/memdb.go, test/integration/get_statvar_group_node_test.go, test/integration/golden_response/get_statvar_group_node/private.json, test/integration/golden_response/get_statvar_group_node/root.json, test/integration/golden_response/get_statvar_group_node/root_mtv.json, test/integration/golden_response/get_statvar_group_node/root_mtv_jpn.json
All the private stat vars are added under "dc/g/Private" categories.
This change makes the private stat vars explorer-able from the hierarchy widget.
=> [Private DC] support stat var group node API

internal/proto/common.pb.go, internal/store/memdb.go, internal/store/memdb_test.go, proto/common.proto, test/integration/golden_response/get_stat_set_series/memdb.json, test/integration/golden_response/get_stat_set_within_place/memdb.json
manifest.json contains the minimal required fields for an import: import_name, provenance_url and data_download_url.
This will be used to populate data metadata field, as well as in the data dashboard (to be implemented)
=> [Private DC] Support manifest.json in the import

internal/server/stat_series.go
We have seen several 200+ seconds latency on this API. Logging the params for better debugging.
=> Add logging to GetStats() API

internal/server/placepage/golden/get_place_page_data/asm.sample.json, internal/server/ranking/ranking.go, internal/server/stat/golden/get_stat_all/result.json, internal/server/stat/golden/get_stat_set/latest.json, internal/server/stat/golden/get_stat_set_series/misc.json, internal/server/stat/golden/get_stat_set_within_place/world_pop.json, scripts/update_golden.sh
Looks like the measurement method is changed from "dcAggregate/CensusACS5yrSurvey" to "CensusACS5yrSurvey". Not sure if this intended? @pradh 
Also fixed a script issue in golden updater.
=> Fix source ranking for CensusACS5YearSurvey_AggCountry

internal/server/node/golden/get_property_values/IG_contained_in_place.json, internal/server/node/golden/get_property_values/IG_contained_in_place_all.json, internal/server/node/golden/get_property_values/IG_limit.json, internal/server/node/golden/get_property_values/IG_location.json, internal/server/node/golden/get_property_values/IG_name.json, internal/server/node/golden/get_property_values_test.go, internal/server/node/property_value.go
Nodes are read from the most preferred group first. When the same node is seen in less preferred group, only add it if it has not been added. 
Note out arcs only get from preferred import group. In arcs are merged across import groups.
=> [Import Group] Merge for property value cache

deploy/base/deployment.yaml, deploy/overlays/local/patch_deployment.yaml, docs/developer_guide.md
A few articles have suggested to remove cpu limit (https://github.com/datacommonsorg/mixer/issues/661). Basically even the cpu is far below limit, it can still get throttled and result in poor performance.
We have seen issues with "/stat-var/group/all" endpoints not returning anything, as the size grows. I tested with `curl http://localhost:8081/stat-var/group/all --output svg.json`. The observation is as follow:
1) The data is read from server cache, so mixer has nothing to read or process.
2) When esp has memory limit of 1G as we have now, it won't return the result, giving error "server didn't response".
3) When esp has memory limit of 2G, it works fine, with the response json size of 226M. As esp has to convert protobuf to JSON and send it out, so 1G of memory could be too tight.
=> Update resource constraint: more memory for esp; remove cpu limit

internal/server/place/golden/get_place_metadata/IG_place-metadata.json, internal/server/place/golden/get_place_metadata_test.go, internal/server/place/places.go
Since place data is in every import group. This picks the most preferred group and only use non-preferred group if it has newer place (in theory this should not happen).
=> Merge for GetPlaceMetadata Cache

internal/server/placepage/place_page.go
- as discussed in [this buganizer](https://b.corp.google.com/issues/220148645#comment5), filter parentPlaces returned by place page api for places that are of a type in the allowlist
=> PlaceType Allowlist for Place Page ParentPlaces

build/ci/cloudbuild.goldendiff.yaml, internal/server/statvar/golden/get_place_statsvar_test.go, internal/server/statvar/golden/get_statvar_group_node_test.go, internal/server/statvar/golden/get_statvar_summary_test.go, scripts/deploy_gke.sh, scripts/golden_diff_notify.sh, scripts/prepare_release.sh, test/e2e/test_driver.go
This is part of clean up task from import group migration. The golden diff email sender should use the import group versions.
=> Update mixer golden diff email and some test suite clean up

deploy/base/deployment.yaml, deploy/overlays/autopush/kustomization.yaml
Too many pods concurrently rolling updates can cause peak resources usages, especially now there is intense computation to build stat var search index. This causes frequent restart and slower completion.
=> Less aggressive rolling update

internal/server/ranking/ranking.go
- NASA_NEXGDDP doesn't exist in the backend any more.
- NASA_NEXDCP30_StatVarSeriesAggr will be replaced by NASA_NEXDCP30_AggrDiffStats.
=> Update ranking imports.

deploy/base/deployment.yaml
startupProbe is available in current GKE cluster (1.21)
=> Use startupProbe for GKE startup status check

deploy/base/deployment.yaml, deploy/overlays/autopush/kustomization.yaml, deploy/overlays/prod/kustomization.yaml
There are increased server restart in deployment which is due to OOM issue. This is due to the increased size of stat var (group) in stat var search computation. 
Longer term, should investigate the bottleneck and make the computation scalable.
=> Increase mixer memory to accomodate for larger stat var (group) size

esp/endpoints.yaml.tmpl, scripts/deploy_gke.sh
From https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#rules_and_selectors, wildcard "*" can only be in the last part of a selector.
Updated to replace the domain in deploy_gke.sh
=> Fix v0 endpoint rule selector issue

deploy/Dockerfile, deploy/cloudbuild.yaml, deploy/push_deploy_tool_image.sh
Add helm to deploy tool so that deploy_gke.sh can use it in automation. Also change docker build -> cloud build for the deployer image.
=> Mixer API split - part 2: Add helm to deploy tool image

scripts/push_binary.sh
Tested: called ./scripts/push_binary.sh (commenting out latest tag so it doesn't create a "latest" image, also commented out update_autopush_version.sh step)
Result
https://pantheon.corp.google.com/gcr/images/datcom-ci/global/datacommons-mixer@sha256:1af99c892362b88675b27d9ba0c56d23d091f6c1e0dc6c73b99eae0784e9edac/details?mods=-monitoring_api_staging&project=datcom-ci
=> Use non-local Cloud Build instead of Cloud Build Local for pushing mixer

deploy/charts/envs/mixer_autopush.yaml, deploy/charts/envs/mixer_encode.yaml, deploy/charts/envs/mixer_private.yaml, deploy/charts/envs/mixer_prod.yaml, deploy/charts/envs/mixer_staging.yaml
This is a follow up from [part 1](https://github.com/datacommonsorg/mixer/pull/902).
This PR migrates [overlaps](https://github.com/datacommonsorg/website/tree/master/deploy/overlays) to value yaml files used by the Helm chart.
- local instance is excluded.
- recon instances are excluded because they are marked to be deleted.
- custom folder is excluded because it is a template.
=> Mixer API split - part 3: Add env speicific values yaml files

cmd/main.go, deploy/helm_charts/envs/mixer_prod.yaml, deploy/helm_charts/mixer/templates/deployment.yaml, deploy/helm_charts/mixer/values.yaml
Add a recon service group which will only serve Recon services (currently all service groups serve recon services).
Tested on dev instance
```
helm upgrade --install mixer-dev deploy/helm_charts/mixer \
--atomic \
-f deploy/helm_charts/envs/mixer_Dev.yaml \
--set mixer.image.tag=45bd8bb \
--set mixer.githash=45bd8bb \
--set-file mixer.schemaConfigs."base\.mcf"=deploy/mapping/base.mcf \
--set-file mixer.schemaConfigs."encode\.mcf"=deploy/mapping/encode.mcf \
--set-file mixer.schemaConfigs."dailyweather\.mcf"=deploy/mapping/dailyweather.mcf \
--set-file mixer.schemaConfigs."monthlyweather\.mcf"=deploy/mapping/monthlyweather.mcf \
--set-file kgStoreConfig.bigqueryVersion=deploy/storage/bigquery.version \
--set-file kgStoreConfig.bigtableImportGroupsVersion=deploy/storage/bigtable_import_group …
```
=> Mixer API split - part 4 : Add a recon service group

build/ci/cloudbuild.push.yaml, deploy/helm_charts/mixer/templates/service.yaml, deploy/overlays/README.md, scripts/deploy_gke.sh, scripts/push_binary.sh
Switch over from kustomize to helm.
Changes:
- Change kustomize commands to helm commands in deploy_gke.sh. After this PR is merged, changes to the clusters will be based on deploy/helm_charts/envs/<env file>.yaml rather than overlays.
- Create a binary before each deployment, and bind the created image to what is deployed ass opposed to always using latest. Tags are easily overwritten and fixing tags to releases stabilizes this.
- Small fix on backend config template: make it release specific.
Tested:
./scripts/deploy_gke.sh mixer_dev 
./scripts/deploy_gke.sh mixer_autopush
=> Mixer API split - part 5 : Switch over to helm in deploy_gke.sh

build/ci/cloudbuild.push.yaml, deploy/helm_charts/envs/mixer_autopush.yaml, deploy/helm_charts/envs/mixer_encode.yaml, deploy/helm_charts/envs/mixer_private.yaml, deploy/helm_charts/envs/mixer_prod.yaml, deploy/helm_charts/envs/mixer_staging.yaml, deploy/helm_charts/mixer/values.yaml
Ingress name is incorrectly set to a fixed "mixer-ingress", causing new loadbalancers to be created instead of updating existing ones.
=> Fix ingress name

cmd/main.go, internal/server/handler.go, internal/server/resource/resource.go, internal/server/server.go, test/setup.go
mixer project will be used to add dynamic Bigtable instance for private DC. 
In a private website deployment, the user created private import cache is stored in the same project as the deployment.
=> Add mixer project to metadata and make variable names more precise

deploy/helm_charts/envs/mixer_autopush.yaml, scripts/deploy_gke.sh
This is a follow up for https://github.com/datacommonsorg/mixer/pull/925
Autopush had too much replicas, resulting in a scheduling failure. Add debug flag to helm to show the exact issues from now on.
=> Fix autopush config, also add debug flag for helm

deploy/helm_charts/envs/mixer_autopush.yaml, deploy/helm_charts/envs/mixer_encode.yaml, deploy/helm_charts/envs/mixer_prod.yaml, deploy/helm_charts/envs/mixer_staging.yaml, deploy/helm_charts/mixer/values.yaml
There have been a lot of webdriver tests failure, which could be due to resource issue in autopush mixer. Create a new group for observations API to narrow down / fix the issue.
=> Make endpoint group for observations API

deploy/helm_charts/mixer/templates/config_maps.yaml
GKE fails to interpret some values due to type mismatches. This happened for example when the githash starts with a number "8734187", 
Failed run
https://pantheon.corp.google.com/cloud-build/builds;region=global/daac272b-a58f-47a8-be18-3f9c91ad4025?mods=-monitoring_api_staging&project=datcom-ci
Tested with manual run
export RELEASE=mixer-autopush
export ENV=mixer_autopush
export TAG=8734187
helm upgrade --install "$RELEASE" deploy/helm_charts/mixer   --atomic   --debug   -f "deploy/helm_charts/envs/$ENV.yaml"   --set mixer.image.tag="$TAG"   --set mixer.githash="$TAG"   --set-file mixer.schemaConfigs."base\.mcf"=deploy/mapping/base.mcf   --set-file mixer.schemaConfigs."encode\.mcf"=deploy/mapping/encode.mcf   --set-file mixer.schemaConfigs."dailyweather\.mcf"=deploy/mapping/dailyweather.mc …
=> Add quote to some helm templated values

deploy/helm_charts/README.md, scripts/deploy_gke.sh
Some builds are timing out. Helm waits for a default of 5min. Immediate solution is to increase this.
Example 
https://pantheon.corp.google.com/cloud-build/builds;region=global/bdd7bfb9-d824-47f9-b7a8-a71c7b35e47c;step=0?mods=-monitoring_api_staging&project=datcom-ci
helm waits for all service groups in series, there's a way to change that.
=> Increase helm timeout from 5min to 10min

deploy/helm_charts/mixer/templates/config_maps.yaml
Reverts datacommonsorg/mixer#947
Unreverting this because the original error, caused by the lack of quotes, came back.
https://pantheon.corp.google.com/cloud-build/builds;region=global/f0148a5c-8ffa-4e3c-a345-dc5dd6f75bd0;step=0?mods=-monitoring_api_staging&project=datcom-ci
=> Revert "Revert "Add quote to some helm templated values""

deploy/helm_charts/mixer/templates/config_maps.yaml
memdbJSON has to be quoted, otherwise the value gets interpreted as nil and causes an error.
https://pantheon.corp.google.com/cloud-build/builds;region=global/6a5d538a-44a4-4e06-9d38-ff50ae6ae919;step=0?mods=-monitoring_api_staging&project=datcom-ci
=> Add quote to memdbJSON

build/ci/cloudbuild.goldendiff.yaml
Copy over base_bigtable_info with tables deleted instead of creating starting from empty file which causes missing information.
=> Fix golden-diff

internal/server/recon/find_entities.go
This PR updates `resolvePlaceIDs()` so that `bulk_find_entities_test.go` passes.
With this change, descriptions that do not map to any dcids are still returned, just without matches (e.g. the "non-existing place wow" case in [/internal/server/recon/bulk_find_entities_test.go:51](https://github.com/datacommonsorg/mixer/blob/ade6e189a0ff2efb251dd32517208cfe5f73d123/internal/server/recon/golden/bulk_find_entities_test.go#L51)
=> Fix failing recon API test

internal/server/v1/propertyvalues/golden/bulk_property_values_in/containedIn1.json, internal/server/v1/propertyvalues/golden/property_values_in/containedIn1.json, internal/server/v1/propertyvalues/heap.go
The same node can appear in different import groups with different names. Should always prefer the highest ranked import group.
=> Property Values nodes merge: prefer highest ranked import group for duplicated nodes

internal/server/statvar/statvar_group.go, test/custom_bigtable_info.yaml
Custom import group does not contains base schemas, so the SVG cache won't have "dc/g/Custom_Root" as child svg of "dc/g/Root".
Here explicitly add this link.
=> [SVG Cache] Link custom root to dc/g/Root

deploy/local/custom_bigtable_info.yaml, deploy/local/deployment.yaml, deploy/local/kustomization.yaml, docs/developer_guide.md, esp/Dockerfile, skaffold.yaml
Mixer GKE deployment has migrated to Helm from Kustomize. 
As the original minikube setup is based on Kustomize, I forked a deployment file under `local` folder. Since the mixer deployment config rarely changes, this fork is okay to maintain.
=> Revive Minikube for local mixer development

internal/server/v1/observations/bulk_point_linked.go, internal/server/v1/observations/golden/bulk_point_linked/all_CA_County.json, internal/server/v1/observations/golden/bulk_point_linked/all_US_State.json, internal/server/v1/observations/golden/bulk_point_linked/all_test.json, internal/server/v1/observations/golden/bulk_point_linked/preferred_CA_County.json, internal/server/v1/observations/golden/bulk_point_linked/preferred_USA_County.json, internal/server/v1/observations/golden/bulk_point_linked/preferred_US_State.json, internal/server/v1/observations/golden/bulk_point_linked/preferred_test.json
Make the code more robust by not relying on cache build behavior as different import groups (place, stat1, stat2) can use different data snapshot
=> Fix bulk linked observation bug

docs/developer_guide.md, esp/envoy-config.yaml
Some requests are massive, ex: http://localhost:8081/v1/bulk/info/variable-group
=> Increase envoy buffer

internal/server/statvar/statvar_group.go, internal/server/statvar/statvar_group_test.go
Currently, if multiple import groups have overlapping schemas, the hierarchy is not merged correctly. 
In addition, even when there is only 1 custom import group, the hierarchy is wrong (See [current stanford instance](https://screenshot.googleplex.com/9EGZoY9CTbhTG3p)).
I can't seem to figure out what determines when a svg shows up in cache (ex: dc/g/Custom_COVID-19_Incidence shows up in deepsolar import?), so a fix for this involves in merging all overlapping stat-vars and child svgs for a particular node, and then recounting all the nodes top down starting from the custom root. 
This fixes current Stanford instance's problem for multiple import groups.
TESTED=[local website, local mixer on envoy](https://screenshot.googleplex.com/3ShFhyPUdPpEM8W)
=> [Custom DC] Fix custom SVG hierarchy

deploy/mapping/kustomization.yaml, deploy/storage/kustomization.yaml
We removed kustomize for mixer, but some are still kept because they're used by https://github.com/datacommonsorg/website/blob/master/deploy/base/kustomization.yaml#L24
=> Remove configmap suffix for kustomize files referenced by website kustomize files.

internal/merger/merger.go, internal/merger/merger_test.go, internal/server/handler_core.go, internal/server/handler_v2.go
Also renamed handler_bigtable.go to handler_core.go, because for Resolve(), it's not just read from Bigtable, but also Maps API, and (in the future) NL APIs.
=> Add merging for resolve results for V2 API.

deploy/helm_charts/envs/mixer_autopush.yaml, deploy/helm_charts/envs/mixer_dev.yaml, deploy/helm_charts/envs/mixer_encode.yaml, deploy/helm_charts/envs/mixer_prod.yaml, deploy/helm_charts/envs/mixer_staging.yaml, deploy/helm_charts/mixer/values.yaml
* Move some of the most used APIs (by traffic) into the dedicated service groups (observation, node)
* Decrease the memory usage for all service group as they are over allocated now
* Decrease pods for "svg" service group as it serves APIs with data in memory with very few computations
* Decrease pods for "default" as it only serves low traffic (and fewer) APIs.
=> Update mixer service group and resource management

deploy/helm_charts/mixer/templates/deployment.yaml, internal/server/server.go
- although configmap won't be created in mixer deployment, in order to use configmap from website deployment, mixer still needs to mount that configmap to a volume.
=> [sv hierarchy] mount blocklist svg to a volume

internal/server/v2/observation/contained_in.go, internal/server/v2/observation/golden/contained_in_latest/read_series_bt.json, internal/server/v2/observation/golden/contained_in_latest_test.go
Copies the BT build rule directly to determine if collection cache exists for a given query. Now the time series cache is read only when needed. 
This saves a lot of processing for places with no data. In some cases, when a lot of variables and child places are involved, OOM can happen but there is no need to fetch the time series data at all.
=> Optimize when to read time series cache for contained in observation query

internal/server/statvar/golden/search_statvar/accommodation_food_services.json, internal/server/statvar/golden/search_statvar/fem.json, internal/server/statvar/golden/search_statvar/female.json, internal/server/statvar/golden/search_statvar/women.json, internal/server/statvar/statvar_group.go, internal/server/v1/info/golden/variable_group_info/demographics.json, internal/server/v1/info/golden/variable_group_info/root.json, internal/server/v1/info/golden/variable_group_info/weather.json, internal/server/v1/info/golden/variable_group_info_test.go, internal/server/v1/propertyvalues/core.go, internal/store/bigtable/group.go, internal/store/bigtable/reader.go, internal/store/bigtable/table.go
SV and SVG in "infrequent" and other import groups could be stale. To prevent them from showing up in the hierarchy and to avoid building the new BT for them, this introduces a way to filter big tables during cache read.
=> Add the ability to use only certain big tables

deploy/storage/base_bigtable_info.yaml, internal/server/v0/triple/golden/get_triples/limit1.json
New frequent release without StormNOAA to fix DroughtEvent:
=> Release Update: frequent 4-Jun-2023

internal/server/handler.go, internal/server/place/places.go, internal/server/server.go, internal/server/v1/info/golden/bulk_place_info/bulk_place_info.json, internal/server/v1/info/place.go, internal/server/v1/propertyvalues/api.go, internal/server/v1/propertyvalues/core.go, internal/server/v1/propertyvalues/linked.go, internal/server/v1/triples/triples.go, internal/server/v2/propertyvalues/api.go
As place info is always set (but only with dcid), it would not fetch remote place info, hence giving incomplete data for custom DC.
The btGroup nil access is result from previous PR.
=> Fix place info merge bug and btGroup nil access bug

internal/server/recon/golden/recognize_places/result.json, internal/server/v2/resolve/golden/resolve_description/city.json, internal/store/files/WorldGeosForPlaceRecognitionAlternateNames.csv, internal/store/files/recog_place_store.go, internal/store/files/recog_place_store_test.go
Add a few names.
Ensure that "New York" maps to the city (like [google](https://www.google.com/search?q=new+york&oq=new+york&gs_lcrp=EgZjaHJvbWUqBwgAEAAYjwIyBwgAEAAYjwIyCggBEC4YsQMYgAQyDQgCEAAYgwEYsQMYgAQyBggDEEUYQDIGCAQQRRhBMgYIBRBFGEAyBggGEEUYPTIGCAcQRRg90gEIMTIxMGowajGoAgCwAgA&sourceid=chrome&ie=UTF-8)).  Otherwise based on population it will always return New York State.
=> RecogPlace: Add support for a side alternateNames file

build/Dockerfile
The newer golang image will introduce this error "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found" in the website-compose build.
=> Fix docker issue with system lib not found

.gitignore, cmd/main.go, internal/server/server.go, internal/store/bigtable/reader.go, internal/store/bigtable/table.go
This issue is uncovered from observation series BT cache read where O(100) variable and O(10) places are queried. In this case, the context used to read Bigtable is canceled after certain amount of read call. This won't be an issue when the variable and place number is small.
In the previous implementation, each Bigtable table has its own client to the instance, thus there are 10+ client from one binary connected to the instance. With this change, there is only one shared client for all the base bigtable (one for each import group). This apparently solves the issue.
=> Fix mixer bigtable read context cancel issue

build/Dockerfile, build/ci/cloudbuild.push.yaml
The old Golang base image has security vulnerability that prevents the GCP project to give IAM access to external account (ex, stanford.edu)
Base mixer image is not used anymore, since the website-compose image (under website repo) will have Golang in it and build mixer binary as well.
=> Update Golang to 1.20.7 to mitigate docker image security issue

esp/endpoints.yaml.tmpl
* This allows the import tool to call into the v2 resolve api.
=> Allow calling V2Resolve without an API key.

internal/store/files/recog_place_store.go, internal/store/files/recog_place_store_test.go
When the query comes in with "sub-saharan africa", NL passes in "sub saharan africa", so in the names replace `-` with space.  Also trim leading spaces when there's multiple names.
I've filed https://github.com/datacommonsorg/mixer/issues/1263 for the parser to be more tolerant.
=> Place Recog: Fix regions some more

deploy/helm_charts/envs/mixer_private.yaml, deploy/helm_charts/mixer/templates/deployment.yaml, deploy/helm_charts/mixer/values.yaml, scripts/deploy_gke.sh, test/setup.go
More details and ration can be found in https://cloud.google.com/endpoints/docs/grpc/get-started-kubernetes-engine-espv2#deploying_the_sample_api_and_esp_to_the_cluster
Also removed deprecated flag from memdb.
=> Migrate ESP to v2 and fixes service management quota issue

deploy/helm_charts/mixer/templates/deployment.yaml
Default size 1Mb is too small for large API response payload
=> [ESP V2] Increase envoy connection buffer limit

internal/util/util.go
Custom DC mixer may have outdated protobuf compared with the remote mixer (main DC API). This prevents mixer error out in such cases.
We should also be more careful on updating and deprecating mixer fields in the future since the mixer response data does persist now, not in storage, but in custom DC.
=> Allow missing field in API response when reading from remote mixer

deploy/helm_charts/mixer/templates/ingress.yaml, deploy/helm_charts/mixer/templates/service.yaml, esp/endpoints.yaml.tmpl
* Add `defaultBackend` field in the ingress so no default backend is created in the load balancer
* Backend-config should point to port 80 instead of 8081. Because of this, the backend config (timeout etc) was not used at all.
* Have a longer timeout for Sparql endpoint and adjust the load balancer <-> backend accordingly. Non Sparql API would still timeout in 60s.
=> Fix and improvement for mixer timeout

deploy/helm_charts/envs/mixer_autopush.yaml, deploy/helm_charts/envs/mixer_prod.yaml, deploy/helm_charts/envs/mixer_staging.yaml
Updates the `multi-domain-<year>` ssl certificates linked in our helm charts from the expired `multi-domain-2022` to the newly created `multi-domain-2024`. A `multi-domain-2024` ssl cert was created for each of their host projects manually in GCP.
=> Update SSL Certificates in helm charts

internal/store/files/EntitiesForPlaceRecognition.csv
SVs with cholera and chickenpox are affected now, biomed is still in early development, so drop the entities to unblock UN launch.
The proper fix might be to flag protect it or not strip biomed entities from SVs.
=> Drop diseases that interfere with SVs

internal/server/recon/coordinate.go, internal/server/recon/golden/resolve_coordinates/result.json, internal/server/recon/golden/resolve_coordinates_test.go
This suggests that the recon coordinate cache is staler than the triples cache, which can happen because the coordinate cache is built on-demand.
The likely sequence of events is that cl/597359495 modified Brazil AA2 geojsons (specifically seems to have removed some boundaries as part of fixing some buggy boundaries), but didn't rebuild the coordinate recon cache.   A fire event located within Brazil AA2 tries to look up the now removed geojson and fails.
Two part fix:
1.  Make the code more resilient
2. Rebuild recon cache
=> Recon:  fix empty array access

internal/server/recon/golden/recognize_entities/result.json, internal/server/recon/golden/recognize_entities_test.go, internal/server/recon/recognize.go
There was a bug in limiting the n-grams used to recognize entities where beyond a certain number of words in the query, the rest of the query was not being used in recognition
=> [recognize entities] fix skipping entities beyond a certain index in the query

internal/merger/merger.go, internal/merger/merger_test.go, internal/server/handler_v2.go, internal/server/place/places.go, internal/util/util.go
When no data is present, the empty data is not nil but rather empty arcs and nodes.
=> Fix empty data check when merging v2 node responses

internal/sqldb/cloudsql/cloudsql.go
* DB name can be configured via a `DB_NAME` env var (defaults to `datacommons`) similar to the [loader](https://github.com/datacommonsorg/import/blob/0162324b5c72a3969bf1d226e0ad027e157c3432/simple/README.md?plain=1#L64).
* @kmoscoe - let's document this variable.
=> Make custom dc db name configurable.

internal/sqldb/createtables.go
* Typically, the tables are first created by mixer.
* Currently, it creates text columns which can't be indexed.
* Changes all columns except `object_value` to varchar so they can be.
* This also makes it consistent with the [loader script](https://github.com/datacommonsorg/import/blob/7d197583b6ad0dfe0568532f919482527c004a8e/simple/stats/db.py#L62-L80).
=> Use varchar vs text columns when creating sql tables.

internal/sqldb/sqlquery/key_value.go
* This fixes the following error when mixer connects to mysql:
```
main.go:237: Failed to create cache: Error 1054 (42S22): Unknown column '$1' in 'where clause'
```
=> Fix mysql error with prepared statement.

internal/store/files/BogusPlaceNames.csv, internal/store/files/WorldGeosForPlaceRecognitionAlternateNames.csv
These names will now require the query to specify county suffix to work.
=> Remove SF and add more bogus names

internal/server/v2/observation/calculation_util.go, internal/server/v2/observation/calculation_util_test.go
Given a formula, returns a Calculation struct which contains 
* AST tree
* Map of leaf data (currently just SV dcid and facet) 
* List of leaf SVs
This follows a lot of logic/tests in Calculator for parsing the tree, except doesn't use a class and doesn't store candidates. (Data candidate handling will be deferred to each caller.)
=> [calculations] Add function to parse AST tree and find leaf SVs

internal/merger/merger.go, internal/merger/merger_test.go
This bug fixes the the root cause of datasets not showing up in custom DC:
Fix: v2/node endpoint wasn't merging properties with the same name and same DCID when data existed both locally and in the remote mixer
Before fix:
```bash
curl "https://dc-autopush-kqb7thiuka-uc.a.run.app/api/node/propvals/in?prop=typeOf&dcids=Source"
{"Source": [{"dcid": "c/s/default"}, {"dcid": "c/s/1"}]}
```
After fix
```bash
curl "http://localhost:8080/api/node/propvals/in?prop=typeOf&dcids=Source"
{
"Source": [
{
"dcid": "c/s/1"
},
{
"dcid": "c/s/default"
},
{
"name": "Australian Bureau of Statistics",
"types": [
"Source"
],
"dcid": "dc/s/AustralianBureauOfStatistics",
"provenanceId": "dc/base/GeneratedGraphs"
},
{
"name": "Brazil INPE - National Institute for Space Research",
"types": [
"Source"
],
"dcid": …
```
=> Fix for merging data in v2/node API

internal/server/statvar/fetcher/formula_fetcher.go, internal/server/v2/observation/golden/calculation/basic.json, internal/server/v2/observation/golden/calculation/two_places.json, internal/server/v2/observation/golden/existence/existence.json, internal/server/v2/resolve/golden/resolve_description/harvard.json
Fixes a bug where the formula_fetcher previously did not include pagination, so only retrieved the first page of formulas. We recently added several hundred more formulas, so need to use pagination to retrieve them all. As part of this change, switches the formula_fetcher to use the triples package directly to make pagination simpler. 
This fixes some goldens that had been empty due to the bug before.
=> Add pagination to formula_fetcher

internal/sqldb/sqlquery/check_svg.go
* Bug: https://issuetracker.google.com/370724577
* For statvar search calls, the input groups are empty which results in a bad sql query causing this issue.
* The fix checks for this condition and returns an empty list which is the correct behavior.
=> Return an empty list of groups if no input groups are specified.

internal/merger/merger.go, internal/merger/merger_test.go, internal/server/handler_v1.go, internal/server/recon/recognize_test.go
Includes responses from both local (custom DC) and remote (base DC) mixers in stat var search. This PR aims to resolve https://b.corp.google.com/issues/370730321
Local testing verified the behavior.
See the two custom DC Stat vars: https://screenshot.googleplex.com/7a3F7W44xGyL5pR
Here is the stat var search: https://screenshot.googleplex.com/BE35RoUiEZhCcUX
=> Joins responses from Remote and Local mixer for SearchStatVar.

internal/util/util.go
* Log tags can be defined as `DCLogTag` enums.
* `DCLog` function can be called to log tagged messages.
* This PR uses the above to log all calls to remote mixer.
+ Example: `[DC][RemoteMixerCall] url=https://api.datacommons.org/v2/node`
+ Currently it only logs the URL being called.
+ We could consider supporting a debug mode and log requests / responses in the future.
=> Create simple utility for logging with tags and log all remote mixer calls.

esp/envoy-config.yaml
* This PR ignores the `key` parameter in the request vs failing requests with that parameter.
* This makes it convenient for users that sometimes copy main dc api urls and use them for their custom dc without updating any parameters. 
+ Currently if the original URL includes a `key` parameter it fails on custom dcs with an obscure 415 error even though the key is not used by custom DCs.
+ With this fix, it will ignore the parameter and proceed with handling the request as usual.
* Fixit task: http://shortn/_9STKYyVCoR
```
~ curl -I -X GET "https://dc-autopush-kqb7thiuka-uc.a.run.app/core/api/v2/node?nodes=Class&property=<-typeOf&key=foo"
HTTP/2 415 
content-type: application/grpc
x-envoy-upstream-service-time: 0
x-cloud-trace-context: e94d41d4dab5d53dba1664ef053c33aa;o=1
date: Tue, 08 Oct …
```
=> Ignore key parameter instead of failing request.

build/ci/cloudbuild.goldendiff.yaml
This will make it easier to filter these if they are ever re-enabled.
=> Update email recipient for golden data diffs

internal/store/files/recon_name_to_types.json
the word "genetic" is a common word to use in queries and should not be recognized as is as an entity
=> Add another entry to recon_name_to_types.json

internal/store/files/recon_name_to_types.json
discovered that "the" is a drugTradeName property value, so adding it to the list of names that need to be preceded by its type
=> add "the" to recon names to types

deploy/storage/spanner_graph_info.yaml, go.mod, go.sum, internal/server/spanner/client.go, internal/server/spanner/golden/query/get_nodes_by_id.json, internal/server/spanner/golden/query_test.go, internal/server/spanner/model.go, internal/server/spanner/query.go, test/setup.go
* Creates a basic spanner client that connects to a cloud spanner graph.
* Implements a simple query that gets nodes by their IDs (does not fetch its edges yet).
* Setup a framework for spanner golden tests.
* Tests are currently no-op by default and require an `ENABLE_SPANNER_GRAPH` variable to be set to `true` for them to be executed.
+ This is to ensure it is only run on workstations of people actively developing against it and does not affect existing tests.
=> Create a basic spanner graph client.

deploy/storage/spanner_graph_info.yaml, internal/server/datasource/datasource.go, internal/server/spanner/datasource.go, internal/server/spanner/dsutil.go, internal/server/spanner/golden/datasource/node.json, internal/server/spanner/golden/datasource_test.go, internal/server/spanner/golden/query/get_node_edges_by_id.json
* The `NodeResponse` does not include name and types currently.
+ Those require graph traversal and will be implemented later.
=> Define a DataSource interface and a basic spanner impl.

cmd/main.go, internal/server/datasource/datasource.go, internal/server/datasources/datasources.go, internal/server/datasources/node/node.go, internal/server/handler_v3.go, internal/server/server.go, internal/server/spanner/datasource.go, internal/server/spanner/dsutil.go, internal/server/spanner/golden/datasource_test.go, internal/server/v3/node/golden/node_test.go, internal/server/v3/node/golden/out_pv_all.json, internal/server/v3/node/node.go, test/setup.go
Uses spanner data source Node implementation for V3 node
This primarily links the V3 node implementation to use the DataSource interface (though currently only spanner is supported) and adds a sample test
* Currently this just reuses the merging logic from V2 (but allows more than two responses). I forked the merging code in case we want to modify it later, independently of V2 (for example, to handle pagination)
* This PR doesn't modify the spanner Node implementation, so the response is still incomplete (doesn't include properties, pagination, or the full EntityInfo). I'll start updating the functionality as a followup
=> Use spanner data source in v3 node

internal/server/spanner/datasource.go, internal/server/spanner/golden/datasource_test.go, internal/server/spanner/golden/query/get_node_edges_by_object_id.json, internal/server/spanner/golden/query/get_node_edges_by_subject_id.json, internal/server/spanner/golden/query_test.go, internal/server/spanner/query.go
Adds base query for in-arcs
Still TODO for Node:
- SingleProp filtering
- Decorators
- BracketProps
- Filters
- Multiple hops
=> Add support for arc direction to v3 node

internal/sqldb/sqlquery/observation.go
This fixes a bug where requesting observations for a date that contains a hyphen (Example: `2024-09`) would return an empty result set.
Before:
```
curl -XPOST "http://localhost:8080/core/api/v2/observation" -d '
{
"select": [
"date",
"value",
"variable",
"entity"
],
"entity": {
"expression": "country/USA<-containedInPlace+{typeOf:State}"
},
"variable": {
"dcids": [
"Count_SubsidizedHousingUnit"
]
},
"date": "2023-12-31"
}
'
```
Returns
```
{"byVariable":{"Count_SubsidizedHousingUnit":{}}}
```
After:
Returns
```
{"byVariable":{"Count_SubsidizedHousingUnit":{"byEntity":{"geoId/40":{"orderedFacets":[{"facetId":"4243125145","observations":[{"date":"2023-12-31","value":53562}],"obsCount":1,"earliestDate":"2023-12-31","latestDate":"2023-12-31"}]},"geoId/41":{"orderedFacets":[{"facetId":"4243125 …
```
=> Quoted date string when fetching obserations

internal/server/node/property_label.go
Updated SQL queries in `GetPropertiesHelper` used by v0, v1, and v2 endpoints to use parameterized queries
=> Paramaterized property_label queries

scripts/update_prod_tag.sh
This is currently available for copy/paste from release documentation but does not take into account that remote names vary.
=> Add script for updating prod tag

internal/server/spanner/golden/query/search_nodes_with_type.json, internal/server/spanner/golden/query/search_nodes_without_type.json, internal/server/spanner/query.go
* Updates node queries to use only GQL. This helps improve performance for querying with filters
* Removes extra join in observation with contained in place query. After speaking with Mingtian, he recommends adding observation to the graph to remove additional joins. This will require updating the graph schema, and there are some implications for write throughput, but we can potentially explore this (can discuss more later)
* Updates some search tests (it's unclear if this is just flaky, so if it starts to fail again, we can consider updating the test to support potentially inconsistent ordering)
=> Update spanner queries

internal/server/v1/propertyvalues/core.go, internal/server/v2/propertyvalues/golden/simple/test_var_2.json
* The current query that fetches triples is executed first, followed by a query to get names and types of all dcids in the triples response.
* Those are then used to populate the names and types of properties in the response.
* Note that if properties reference entities in base DC, those will not be fetched and will continue to be returned as they currently are. 
+ If we need their names / types to also be fetched, that will have to be done via a separate remote mixer call.
+ We can implement this in a separate PR if necessary.
=> Return names and actual types of properties.

cmd/main.go, internal/server/count/count.go, internal/server/handler_v1_test.go, internal/server/node/property_label.go, internal/server/placein/placein.go, internal/server/statvar/fetcher/entity_sv_fetcher.go, internal/server/statvar/fetcher/svg_fetcher.go, internal/server/statvar/statvar_summary.go, internal/server/v0/propertylabel/property_label_test.go, internal/server/v1/observationdates/observation_dates_linked.go, internal/server/v1/propertyvalues/core.go, internal/server/v2/facet/series.go, internal/server/v2/observation/contained_in.go, internal/server/v2/shared/contained_in_test.go, internal/store/store.go, test/setup.go
* Maintains SQLClient in the store by value instead of by reference. This avoids NPEs with the underlying DB handle.
* We'll switch back to pointer reference once the DB handle in the client is made internal.
=> Fix nil references to sql DB.

internal/sqldb/model.go
* GROUP_CONCAT values are returned as strings by sqlite but as byte arrays by mysql (cloud sql).
* This led to errors (see image below).
* This was not caught by golden tests since they use sqlite.
=> Fix error due to value being returned as byte array by mysql.

internal/server/statvar/golden/search_statvar/no-sql-groups-test-case.json, internal/server/statvar/golden/search_statvar_test.go, internal/sqldb/query.go
Fixes the following cdc autopush failure:
Which stems from this website api error:
Which stems from this mixer error:
Which is now fixed in the local instance:
Also added a test case for this.
=> Fix existing sv groups sql call to work with empty arrays.

cmd/main.go, internal/server/cache/cache.go, internal/server/handler.go, internal/sqldb/client.go, internal/sqldb/model.go, internal/sqldb/query.go, internal/sqldb/sqlquery/entity_variable_existence.go, internal/sqldb/sqlquery/get_import_table.go, internal/sqldb/sqlquery/get_import_table_test.go, internal/sqldb/sqlquery/get_provenance.go, internal/sqldb/statements.go
* All queries are now encapsulated!
* Removed the public DB variable from the client since it's no longer needed.
* One remaining thing is to use a SQLClient pointer (vs by value) in the store - will do that in the next PR.
=> Encapsulate all remaining queries in sql client.

cmd/main.go, internal/server/dispatcher/dispatcher.go, internal/server/handler_v3.go, internal/server/server.go, internal/server/v3/observation/calculation.go, test/setup.go
* Introduced a `Dispatcher` for managing a request's lifecycle - pre-processing, handling, post-processing.
+ Could have done this in the handler itself but a standalone struct allows us to test it independent of a server.
* Introduced a `Processor` interface that can be implemented for pre and post processing.
* Created a no-op `CalculationProcessor` as an example.
+ To be replaced with a real implementation subsequently.
* Made a pragmatic call to use casting to get to the concrete request and response types.
+ See code comments for details.
=> Create a dispatcher framework for managing request lifecycle.

internal/server/spanner/golden/query/get_node_edges_in_chain.json, internal/server/spanner/golden/query/get_node_edges_out_chain.json, internal/server/spanner/statements.go
Use "match any" instead of "distinct" which has slightly better performance.
(Also one nice side effect is that now we can return types! I can update V2 to match as a follow up)
=> Update chain query

internal/server/ranking/ranking.go, internal/server/v2/facet/golden/series_facet/series_facet_test_ranking.json, internal/server/v2/facet/golden/series_facet_test.go
Update facet ranking to take import name into account because some facets differ by only the import name. This non-deterministic ranking of facets causes flaky NL tests in the website repository because NL chooses the top ranked facet.
=> Fix non deterministic facet ranking

internal/server/spanner/datasource.go
This is to match the behavior of V2 which returns the same error for large requests (e.g. Count_Person for country/USA<-containedInPlace+{typeOf:City}) to prevent timeouts/memory limits: https://github.com/datacommonsorg/mixer/blob/master/internal/server/v2/observation/contained_in.go#L160
Currently the limit is set to the same as V2 (5000 series per response)
=> Add observation response limits to spanner

internal/server/spanner/datasource.go
Reverts datacommonsorg/mixer#1523
This limit is actually too restrictive compared to V2, since many containedInPlace requests are precomputed in cache. Instead we can find a better way to handle timeouts
=> Revert "Add observation response limits to spanner"

tools/clearcache/clear_autopush.sh, tools/clearcache/run.sh
* `run.sh` looks up the redis host for a given region and calls the go utility to clear the cache on that host.
* `clear_autopush.sh` calls `run.sh` for the autopush mixer.
+ Need to figure out a way for this to be invoked automatically on deployment.
* Verified it by running `clear_autopush.sh` from my machine. Here's the output:
```
$ ./tools/clearcache/clear_autopush.sh
Updated property [core/project].
Fetching cluster endpoint and auth data.
kubeconfig entry generated for mixer-us-central1.
Clearing Redis cache for datcom-mixer-autopush/mixer-us-central1/us-central1, redis host: 10.244.163.180, using pod: mixer-autopush-default-6cbc8896f-4b29s
Defaulted container "mixer" out of: mixer, esp
Cleared redis cache: 10.244.163.180:6379
```
=> Create script to clear redis cache.

cmd/main.go, internal/merger/merger.go, internal/server/datasources/datasources.go, internal/server/v2/graph.go, internal/server/v3/node/golden/in_prop.json, internal/server/v3/node/golden/node_test.go, internal/server/v3/node/golden/out_prop.json, internal/server/v3/node/golden/out_pv_all.json, internal/sqldb/client.go, internal/sqldb/datasource.go, internal/sqldb/dsutil.go, test/setup.go
* Creates and adds a sql datasource if v3 is enabled and sql params are configured both for runtime and golden tests.
* Implements the node properties request.
* Fixes some response merge logic.
=> Support node properties request in sql datasource.

internal/server/spanner/statements.go, internal/server/v3/node/golden/in_chain_filter.json, internal/server/v3/node/golden/in_filter.json, internal/server/v3/node/golden/node_test.go
Fixes error with chain and filters for V3 node
Also optimizes the containedInPlace V3 observation query
However, the chained query for getting states in USA (nodes=country/USA&property=<-containedInPlace+{typeOf:State}) still time outs. This is because there's a huge number of places in USA. I was wondering if it's worth to just switch all <-containedInPlace+ node queries to <-linkedContainedInPlace internally (like we do for /v3/observation) since this is a pretty common use case - wdyt?
=> V3 node chain fix

cmd/main.go, internal/sqldb/datasource.go, internal/sqldb/datasource_test.go, test/setup.go
* The sql data source will need a secondary data source (typically a remote mixer) to fetch certain data (e.g. [child places](https://github.com/datacommonsorg/mixer/blob/f9709fd33930b976b525569a353e3db5a03ccd5f/internal/server/v2/observation/contained_in.go#L196))
* The PR simply wires a secondary data source to the sql data source (remote for main, spanner for tests) and does not use it yet.
* It will be used in a follow-up PR that implements contained in place in the sql data source.
=> Configure sql data source with a secondary data source.

internal/server/v2/facet/contained_in.go, internal/server/v2/facet/golden/contained_in_facet/US_State.json, internal/server/v2/facet/golden/contained_in_facet_test.go, internal/server/v2/observation/contained_in.go, internal/server/v2/observation/helper/helper.go, internal/server/v2/observation/observation.go, internal/server/v2/shared/shared.go
* Context: https://issuetracker.google.com/issues/400486979#comment2
* Moved observation helpers for sql under a different package to avoid a cycle.
```
$ curl -X POST \
-H "Content-Type: application/json" \
-d '{
"select": ["variable", "entity", "facet"],
"entity": {
"expression": "Earth<-containedInPlace+{typeOf:Country}"
},
"variable": {
"dcids": ["gender_wage_gap"]
},
"date": ""
}' \
https://dc-autopush-kqb7thiuka-uc.a.run.app/core/api/v2/observation
{"byVariable":{"gender_wage_gap":{"byEntity":{"":{}}}}}
```
```
curl -X POST \
-H "Content-Type: application/json" \
-d '{
"select": ["variable", "entity", "facet"],
"entity": {
"expression": "Earth<-containedInPlace+{typeOf:Country}"
},
"variable": {
"dcids": ["gender_wage_gap"]
},
"date": ""
}' \
http://localhost:8081/v2/observation …
```
=> Add support for facet requests for sql backends.

internal/server/spanner/datasource.go, internal/server/spanner/dsutil.go, internal/server/spanner/golden/query/get_observations_entity.json, internal/server/spanner/golden/query_test.go, internal/server/spanner/query.go, internal/server/spanner/statements.go, internal/server/v3/observation/golden/observation_test.go, internal/server/v3/observation/golden/observations_entity.json, internal/server/v3/observation/golden/observations_existence_entity.json, internal/server/v3/observation/golden/observations_facet_entity.json
This is for requests of the form /observation?entity.dcids=<> where no variable is specified, so essentially getting the variables for a place(s). 
Kara brought up that this is supported in V2, but we noticed it wasn't yet supported it in V3. In V2, this only works for existence and not with any date or facet filters (so it's a bit inconsistent). Here I added it everywhere, but can restrict it if needed as a follow up, along with some other query optimizations 
This PR also splits up some tests into different tests to avoid test timeouts
=> Add entity existence requests to V3 observation

internal/merger/merger.go, internal/merger/merger_test.go
Fixes an bug with merging where some data was being deleted
This was causing some custom dc node responses to be incomplete
Tested with unit tests and with local custom dc mode
=> fix bug in merging node responses

internal/server/spanner/datasource.go, internal/server/spanner/dsutil.go, internal/server/spanner/golden/query/get_observations_entity.json, internal/server/spanner/golden/query_test.go, internal/server/spanner/model.go, internal/server/spanner/query.go, internal/server/spanner/statements.go, internal/server/v3/observation/golden/observation_test.go, internal/server/v3/observation/golden/observations_entity.json, internal/server/v3/observation/golden/observations_existence_entity.json, internal/server/v3/observation/golden/observations_facet_entity.json
This is to make the results from spanner smaller for existence requests that don't need them 
(note: some of the tests got updated with some temperature data since I added it to the test instance, but that's unrelated to this change)
=> filter observations from spanner for existence requests

internal/server/spanner/golden/query/search_nodes_with_type.json, internal/server/spanner/golden/query/search_nodes_without_type.json, internal/server/spanner/golden/query/search_object_values_with_query_and_type.json, internal/server/spanner/statements.go, internal/server/v3/nodesearch/golden/node_search_with_query_and_type.json
This is to fix the broken "series" query
Also regenerates some goldens since it looks like the order was updated (unrelated to this change, possibly due to indexing)
=> Add defaults to node search queries

deploy/helm_charts/envs/mixer_autopush.yaml
After deployment:
- The Google-built OTLP collector should be running in datcom-mixer-autopush
- The autopush mixer should be pushing metrics to it
- These metrics should be discoverable in Cloud Monitoring
=> Enable metrics in mixer autopush

deploy/Dockerfile
While it wasn't in the previous config, the previously pushed version of the image did have Docker. This inclusion is required for Custom DC autopush deployments.
=> Include Docker in the deploy-tool image

internal/sqldb/query.go, internal/sqldb/statements.go
* `GROUP_CONCAT` was returning truncated results which caused issues with entities with a high number of variables
* See https://issuetracker.google.com/issues/443752806 for more details
* This PR updates the sql query to not use `GROUP_CONCAT`.
=> Do not use GROUP_CONCAT when fetching entity variables

deploy/apigee/README.md, deploy/apigee/deploy_apigee.sh
- Use a plan file to guarantee that the changes applied are always the ones that were previewed
- Check that tfstate is read from a bucket with the expected name
- Document that the bucket name should be updated when setting up a new Apigee organization
=> Improve Apigee deployment script robustness

build/ci/cloudbuild.deploy_flags.yaml
- The deploy script looks for $BUILD_ID to know whether it's running on Cloud Build (it asks for confirmation otherwise)
- `validate-feature-flags` isn't a standalone step anymore, it's built into the deploy script
=> [Feature Flags] Fix Cloud Build trigger definition
